# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf65f7e420c05f606dae0a14a26554f2a0af69101b7fd972e6fdae879436851d8a5067fe62a8ff4f9d7050a581c57edac7a5a3aa3897b85e7f9f63f378fd6f55

test:
  secret_key_base: 400bcac6b808476bdf204c7473c5f17d6be6b86c570bd92e849ed376de5047d2a071759692f2cbe1084d0d6ada6942826545b9118a6cf1e1540767a0ef457c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
